POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRpZ3JhbkBnbWFpbC5jb20iLCJpZCI6MiwiaWF0IjoxNjk4NzIwMjE4fQ.aJg6YJoCXT_A24XKssEWS8Cl4jhE0q5Lnu4wvZVDsz0

{
    "author":"Lilac Saika",
    "url": "www.google.com",
    "title": "Falling Sakura",
    "year": "2023"
}

###
DELETE http://localhost:3001/api/blogs/6
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRpZ3JhbkBnbWFpbC5jb20iLCJpZCI6MiwiaWF0IjoxNjk4NzIwMjE4fQ.aJg6YJoCXT_A24XKssEWS8Cl4jhE0q5Lnu4wvZVDsz0

###
PUT http://localhost:3001/api/blogs/10
Content-Type: application/json

{
    "likes": "7"
}
